### ISSUE TITLE
How does this calculate WPM?

### ISSUE THREAD

**Issue by MoltenMonster** [wilmerterrero/MacWPM#1]
The app seems to measure WPM much in a non-standard way, differently compared to sites like TypingClub.com and Monkeytype.com, it would be nice if there was a setting for how WPM is calculated, so I could make it calculate WPM like those sites and easily compare my typing speed.

**Comment by wilmerterrero** [comment]
It uses this formula:
![image](https://github.com/wilmerterrero/MacWPM/assets/59232366/58a1f712-31d6-4794-97b6-56cf752f0773)
